### ISSUE TITLE
error-invalid-room

### ISSUE THREAD

**Issue by Naguchennai** [sacOO7/RocketChat-Android-Demo#1]
Message is {"msg":"result","id":"6","error":{"error":"error-invalid-room","reason":"Invalid room","details":{"method":"canAccessRoom"},"message":"Invalid room [error-invalid-room]","errorType":"Meteor.Error"}}

also room name not show

`06-16 19:16:25.628 26165-26213/io.rocket.chat I/System.out: Message is {"msg":"updated","methods":["9"]}
06-16 19:16:25.628 26165-26213/io.rocket.chat W/System.err: org.json.JSONException: No value for result
06-16 19:16:25.628 26165-26213/io.rocket.chat W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
06-16 19:16:25.628 26165-26213/io.rocket.chat W/System.err:     at org.json.JSONObject.getJSONObject(JSONObject.java:609)
06-16 19:16:25.628 26165-26213/io.rocket.chat W/System.err:     at io.rocket.chat.Activities.ChatActivity$4.call(ChatActivity.java:170)
06-16 19:16:25.628 26165-26213/io.rocket.chat W/System.err:     at com.chat.Socket$13.onTextMessage(Socket.java:380)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:262)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:240)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:965)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:748)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
06-16 19:16:25.629 26165-26213/io.rocket.chat W/System.err:     at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
06-16 19:16:25.629 26165-26213/io.rocket.chat I/System.out: Message is {"msg":"result","id":"9","error":{"error":"error-invalid-room","reason":"Invalid room","details":{"method":"canAccessRoom"},"message":"Invalid room [error-invalid-room]","errorType":"Meteor.Error"}}
06-16 19:16:25.713 26165-26165/io.rocket.chat E/Keyboard: close`

**Comment by sacOO7** [comment]
You had entered correct username and password?
